// <auto-generated />
using BlazorApp.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.EntityFramework.Migrations
{
    [DbContext(typeof(LayoutDbContext))]
    partial class LayoutDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.FieldEditDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldTypeDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LayoutType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FieldTypeDefinitionId");

                    b.ToTable("FieldEditDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "ボタンラベル",
                            DisplayOrder = 1,
                            FieldTypeDefinitionId = 1,
                            IsRequired = true,
                            LayoutType = 0
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "ラベル表示文字",
                            DisplayOrder = 1,
                            FieldTypeDefinitionId = 1,
                            IsRequired = true,
                            LayoutType = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "画像URL",
                            DisplayOrder = 1,
                            FieldTypeDefinitionId = 2,
                            IsRequired = true,
                            LayoutType = 2
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "代替テキスト",
                            DisplayOrder = 2,
                            FieldTypeDefinitionId = 3,
                            IsRequired = false,
                            LayoutType = 2
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "リンク先URL",
                            DisplayOrder = 1,
                            FieldTypeDefinitionId = 4,
                            IsRequired = true,
                            LayoutType = 3
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "リンクの開き方",
                            DisplayOrder = 2,
                            FieldTypeDefinitionId = 5,
                            IsRequired = false,
                            LayoutType = 3
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "リンクテキスト",
                            DisplayOrder = 3,
                            FieldTypeDefinitionId = 1,
                            IsRequired = true,
                            LayoutType = 3
                        });
                });

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.LayoutFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldTypeDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UILayoutBaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldTypeDefinitionId");

                    b.HasIndex("UILayoutBaseId", "FieldTypeDefinitionId")
                        .IsUnique();

                    b.ToTable("LayoutFieldValue");
                });

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.LayoutSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeightPerCell")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScreenHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScreenWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WidthPerCell")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("LayoutSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColumnNumber = 10,
                            HeightPerCell = 100,
                            Number = 1,
                            RowNumber = 10,
                            ScreenHeight = 600,
                            ScreenWidth = 400,
                            ThemeId = 1,
                            WidthPerCell = 100
                        });
                });

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.UIBaseLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CssJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LayoutType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StyleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WrapperStyleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("UIBaseLayouts");
                });

            modelBuilder.Entity("FieldTypeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputType")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FieldTypeDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultDisplayName = "表示テキスト",
                            DisplayOrder = 1,
                            InputType = "text",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            DefaultDisplayName = "画像ソース",
                            DisplayOrder = 2,
                            InputType = "text",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            DefaultDisplayName = "代替テキスト",
                            DisplayOrder = 3,
                            InputType = "text",
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            DefaultDisplayName = "リンク先URL",
                            DisplayOrder = 4,
                            InputType = "text",
                            Type = 4
                        },
                        new
                        {
                            Id = 5,
                            DefaultDisplayName = "リンクの開き方",
                            DisplayOrder = 5,
                            InputType = "select",
                            Type = 5
                        },
                        new
                        {
                            Id = 6,
                            DefaultDisplayName = "ツールチップ",
                            DisplayOrder = 6,
                            InputType = "text",
                            Type = 6
                        });
                });

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.FieldEditDefinition", b =>
                {
                    b.HasOne("FieldTypeDefinition", "FieldType")
                        .WithMany()
                        .HasForeignKey("FieldTypeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldType");
                });

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.LayoutFieldValue", b =>
                {
                    b.HasOne("FieldTypeDefinition", "FieldDefinition")
                        .WithMany()
                        .HasForeignKey("FieldTypeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp.EntityFramework.Models.UIBaseLayout", "BaseLayout")
                        .WithMany("FieldValues")
                        .HasForeignKey("UILayoutBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseLayout");

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.LayoutSection", b =>
                {
                    b.HasOne("BlazorApp.EntityFramework.Models.Theme", "Theme")
                        .WithMany("LayoutSections")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.UIBaseLayout", b =>
                {
                    b.HasOne("BlazorApp.EntityFramework.Models.LayoutSection", "Page")
                        .WithMany("Layouts")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.LayoutSection", b =>
                {
                    b.Navigation("Layouts");
                });

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.Theme", b =>
                {
                    b.Navigation("LayoutSections");
                });

            modelBuilder.Entity("BlazorApp.EntityFramework.Models.UIBaseLayout", b =>
                {
                    b.Navigation("FieldValues");
                });
#pragma warning restore 612, 618
        }
    }
}
